apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: email-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-service
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 80